---
  - hosts: 127.0.0.1
    connection: local

    vars:
      dev_env_dir: /opt/startupper

    tasks:
      - name: Install general programs
        community.general.homebrew_cask:
          name:
            - slack
            - google-chrome
            - arc
            - firefox
            - bitwarden
            - miro
            - hot
            - clickup
            - homebrew/cask-versions/tunnelblick-beta
            - hiddenbar
          state: present
      - name: Install "nerds" system packages
        community.general.homebrew:
          name:
            - neofetch
            - thefuck
            - yadm
          state: present
